### PR TITLE
Initial commit Margie

### PR DESCRIPTION
**Pull request by maggan1968**
hello gays, How is your crypto?

### CODE REVIEW

**Comment by IrynM** [comment]
Margie looks good

**Review by IrynM — APPROVED** [review]
all good

**Review by nilufarmirzoeva — APPROVED** [review]
Approved Nilufar

**Review by AzizaMir26 — APPROVED** [review]
good

**Review by IgorL1991 — APPROVED** [review]

**Review by veselamilcheva1 — APPROVED** [review]
Good job

**Pull request merged**
